springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
jwt:
  token:
    key: D28D12AFE1FC18B5AC5F25C2889F2
